# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 10:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('add_date', models.DateTimeField(verbose_name='Date Added')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('create_date', models.DateTimeField(verbose_name='Create Date')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('completed_date', models.DateTimeField(verbose_name='Completed Date')),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MODERATE', 'Moderate'), ('LOW', 'Low')], default='HIGH', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='OPEN', max_length=20)),
                ('component', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('TRAVEL', 'Travel'), ('TERM_LIFE', 'Term Life'), ('HEALTH', 'Health'), ('CFSUPPORT', 'CF Support'), ('WEBSITE', 'Website'), ('ULTRON', 'Ultron')], default='CAR', max_length=20)),
                ('asana_task', models.URLField(blank=True, max_length=100, null=True)),
                ('pull_request', models.URLField(blank=True, max_length=500, null=True)),
                ('test_link', models.URLField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('business_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_manager', to=settings.AUTH_USER_MODEL)),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
    ]
