# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 10:35
from __future__ import unicode_literals
import logging

from django.db import migrations
from django.contrib.auth.models import Group, Permission


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

all_permission = Permission.objects.all()


def add_group_permissions(app, schema_editor):
    group, created = Group.objects.get_or_create(name='developer')
    if created:
        for p in all_permission:
            group.permissions.add(p)
        logger.info('Group created')

    group, created = Group.objects.get_or_create(name='qa')
    if created:
        for p in all_permission:
            group.permissions.add(p)
        logger.info('Group created')

    group, created = Group.objects.get_or_create(name='project_manager')
    if created:
        for p in all_permission:
            group.permissions.add(p)
        logger.info('Group created')

    group, created = Group.objects.get_or_create(name='business_manager')
    if created:
        for p in all_permission:
            group.permissions.add(p)
        logger.info('Group created')


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
